apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ required "secrets.jwtSecretKey is required" .Values.secrets.jwtSecretKey | quote }}
  DEFAULT_ADMIN_USERNAME: {{ required "secrets.adminUsername is required" .Values.secrets.adminUsername | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ required "secrets.adminPassword is required" .Values.secrets.adminPassword | quote }}
  {{- if .Values.postgresql.auth.password }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
