apiVersion: 1
providers:
  - name: SentinelForge
    orgId: 1
    folder: SentinelForge
    type: file
    disableDeletion: false
    editable: true
    updateIntervalSeconds: 30
    options:
      path: /etc/grafana/provisioning/dashboards/sentinelforge
      foldersFromFilesStructure: false
